name: Notify

on:
  push:

jobs:
  notify:
    uses: fridfn/workflow-development/.github/workflows/telegram.yml@main
    with:
      private_message: |
        💜 Repo: ${{ github.repository }}
        👤 Author: ${{ github.actor }}
        📝 Commit: ${{ github.event.head_commit.message }}

      channel_message: |
        🚀 Update baru di ${{ github.repository }}

    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
